depreciate_worker:
  cron: "*/1 * * * *" #it will search depreciate car price every minute - Real time is two months
  #cron: "0 0 1 * *" #Real time is one month “At 00:00 on day-of-month 1.”
  class: "DepreciateWorker"